#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ttylog
version:      0.82
version_from: ttylog
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
